### ISSUE TITLE
Clash parser 相关疑问

### ISSUE THREAD

**Issue by Les1ie** [pompurin404/override-hub#1]
好像不能直接使用 yaml 格式的 clash parser，如 [Parser-for-clash](https://github.com/iczrac/Parsers-for-clash) 这个项目中提供的 yaml 文件。

大佬能否提供一个适配的思路或者脚本。

**Comment by pompurin404** [comment]
看文档，这是clash-for-windows的，当然不支持

**Comment by Les1ie** [comment]
感谢大佬回复。
我对`mihomo`、`clash`、`v2ray`等项目的了解比较有限，只简单地用过`clash for windows`。
所以想问下您，`mihomo-party`所支持的yaml/json覆写语法是怎样的呢？如果是和其他项目的语法相同，能否指个路，我自己去找找资料。

**Comment by xishang0128** [comment]
> 感谢大佬回复。 我对`mihomo`、`clash`、`v2ray`等项目的了解比较有限，只简单地用过`clash for windows`。 所以想问下您，`mihomo-party`所支持的yaml/json覆写语法是怎样的呢？如果是和其他项目的语法相同，能否指个路，我自己去找找资料。

https://mihomo.party/guides/function/override/yaml/

**Comment by Les1ie** [comment]
> > 感谢大佬回复。 我对`mihomo`、`clash`、`v2ray`等项目的了解比较有限，只简单地用过`clash for windows`。 所以想问下您，`mihomo-party`所支持的yaml/json覆写语法是怎样的呢？如果是和其他项目的语法相同，能否指个路，我自己去找找资料。
> 
> https://mihomo.party/guides/function/override/yaml/

噢，感谢
